# Generated by Django 3.0.5 on 2020-04-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200420_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
